spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSecret: ${JWT_REFRESH_SECRET}
  time:
    accessTime: ${JWT_ACCESS_TIME}
    refreshTime: ${JWT_REFRESH_TIME}

gauth:
  clientId: ${GAUTH_CLIENTID}
  clientSecret: ${CLIENT_SECRET}
